variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - caching
  - verify
  - test
  - build
  - cypress
  - deploy

caching:
  image: node:22-bullseye-slim
  stage: caching
  before_script:
    # update environment
    - apt update
    - npm i -g typescript
    - npm install -g corepack@latest
    - corepack enable pnpm
  script:
    # install dependencies
    - pnpm install
  cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push

verify:
  image: node:22-bullseye-slim
  stage: verify
  needs: [caching]
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  before_script:
    - npm i -g prettier@3.5.3
    - npm install -g corepack@latest
    - corepack enable pnpm
  script:
    # run prettier and lint
    - prettier -c .
    - pnpm lint

vitest:
  image: node:22-bullseye-slim
  stage: test
  needs: [caching, verify]
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
    paths:
      - coverage/
      - node_modules/
  before_script:
    - npm install -g corepack@latest
    - corepack enable pnpm
  script:
    # run test with coverage
    - pnpm vitest run --coverage
  coverage: '/Statements\s*: \d+\.\d+/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura # or jacoco
        path: coverage/vitest/clover.xml

#coverage:
#  image: node:22-bullseye-slim
#  stage: test
#  needs: [caching, verify, cypress, vitest]
#  cache:
#    # inherit all global cache settings
#    <<: *global_cache
#    # override the policy
#    policy: pull
#  script:
#    # run prettier and lint
#    - chmod +x gitlab-ci.coverage.sh
#    - ./gitlab-ci.coverage.sh
#  artifacts:
#    reports:
#      coverage_report:
#        coverage_format: cobertura # or jacoco
#        path: coverage/cy-coverage/clover.xml

build:
  image: node:22-bullseye-slim
  stage: build
  needs: [caching, verify, vitest]
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
    paths:
      - .next/
      - node_modules/
  before_script:
    - npm i -g typescript
    - npm install -g corepack@latest
    - corepack enable pnpm
  script:
    # compile typescript and build project
    - tsc --noEmit
    - pnpm build

cypress:
  image: cypress/browsers:22.12.0
  stage: cypress
  needs: [caching, verify, vitest, build]
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
    paths:
      - node_modules/
      - .next/
  before_script:
    - npm install -g corepack@latest
    - corepack enable pnpm
  script:
    # install cypress binary
    - pnpm cypress install
    # start the server in the background
    - pnpm start &
    # run Cypress tests e2e
    - npx cypress run --browser firefox
    # run Cypress tests e2e
    - npx cypress run --component
  artifacts:
    when: on_failure
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
    reports:
      coverage_report:
        coverage_format: cobertura # or jacoco
        path: coverage/cy-coverage/clover.xml

deploy:
  image: docker:20.10.16
  stage: deploy
  needs: [caching, verify, cypress, vitest, build]
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - tags
  except:
    - branches

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created
  script:
    - echo "releasing $CI_COMMIT_TAG"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
